def model_info():
  model_compile_config = {'optimizer': 'adam',
                          'loss': 'binary_crossentropy',
                          'metrics': ['accuracy'],
                          'loss_weights': None,
                          'weighted_metrics': None,
                          'run_eagerly': None,
                          'steps_per_execution': None,
                          'jit_compile': None}

  model_config = {'name': 'sequential',
                  'layers': [{'module': 'keras.layers',
                              'class_name': 'InputLayer',
                              'config': {'batch_input_shape': [None, 12338],
                                         'dtype': 'float32',
                                         'sparse': False,
                                         'ragged': False,
                                         'name': 'input_1'},
                              'registered_name': None},
                             {'module': 'keras.layers',
                              'class_name': 'Dense',
                              'config': {'name': 'dense',
                                         'trainable': True,
                                         'dtype': 'float32',
                                         'units': 64,
                                         'activation': 'relu',
                                         'use_bias': True,
                                         'kernel_initializer': {'module': 'keras.initializers',
                                                                'class_name': 'GlorotUniform',
                                                                'config': {'seed': None},
                                                                'registered_name': None},
                                         'bias_initializer': {'module': 'keras.initializers',
                                                              'class_name': 'Zeros',
                                                              'config': {},
                                                              'registered_name': None},
                                         'kernel_regularizer': None,
                                         'bias_regularizer': None,
                                         'activity_regularizer': None,
                                         'kernel_constraint': None,
                                         'bias_constraint': None},
                              'registered_name': None,
                              'build_config': {'input_shape': [None, 12338]}},
                             {'module': 'keras.layers',
                              'class_name': 'Dense',
                              'config': {'name': 'dense_1',
                                         'trainable': True,
                                         'dtype': 'float32',
                                         'units': 32,
                                         'activation': 'relu',
                                         'use_bias': True,
                                         'kernel_initializer': {'module': 'keras.initializers',
                                                                'class_name': 'GlorotUniform',
                                                                'config': {'seed': None},
                                                                'registered_name': None},
                                         'bias_initializer': {'module': 'keras.initializers',
                                                              'class_name': 'Zeros',
                                                              'config': {},
                                                              'registered_name': None},
                                         'kernel_regularizer': None,
                                         'bias_regularizer': None,
                                         'activity_regularizer': None,
                                         'kernel_constraint': None,
                                         'bias_constraint': None},
                              'registered_name': None,
                              'build_config': {'input_shape': [None, 64]}},
                             {'module': 'keras.layers',
                              'class_name': 'Dense',
                              'config': {'name': 'dense_2',
                                         'trainable': True,
                                         'dtype': 'float32',
                                         'units': 1,
                                         'activation': 'sigmoid',
                                         'use_bias': True,
                                         'kernel_initializer': {'module': 'keras.initializers',
                                                                'class_name': 'GlorotUniform',
                                                                'config': {'seed': None},
                                                                'registered_name': None},
                                         'bias_initializer': {'module': 'keras.initializers',
                                                              'class_name': 'Zeros',
                                                              'config': {},
                                                              'registered_name': None},
                                         'kernel_regularizer': None,
                                         'bias_regularizer': None,
                                         'activity_regularizer': None,
                                         'kernel_constraint': None,
                                         'bias_constraint': None},
                              'registered_name': None,
                              'build_config': {'input_shape': [None, 32]}}]}

  return model_config, model_compile_config